services:
  _defaults:
    autowire: true

  App\:
    resource: '../src/*'

  App\Controller\OrderController:
    public: true

  App\Listeners\OrderSmsListener:
    tags:
      [
        {
          name: 'app.event_listener',
          event: order_after_insert,
          method: sendToCustomer,
          priority: 3,
        },
      ]

  App\Listeners\OrderEmailSubscriber:
    tags: ['app.event_subscriber']

  Symfony\Component\EventDispatcher\EventDispatcher: ~
